apiVersion: apps/v1
kind: Deployment
metadata:
  name: viya-dev-website
  labels:
    {{- include "viya-dev-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "viya-dev-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "viya-dev-website.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
